import { PRODUCT_NAME, PRODUCT_SUBDOMAIN } from "@/config/product";
import type { Pillar, ReportModel } from "@/lib/report-core/types";

/**
 * Build the constructive per-pillar fix-issue body (work-order §4c / §6.3) — PURE + deterministic.
 * ONE issue per pillar: the pillar's fixes under its title, plus the required "assessed via
 * TrustScope" attribution footer (the reputation mechanism). Phrased as optional suggestions,
 * never demands. Only DISPLAYED pillars ever reach this (Functional Quality is never shown), so
 * no Pro-only signal can leak into a filed issue.
 */

const url = () => `https://${PRODUCT_SUBDOMAIN}`;

function issueIntro(report: ReportModel): string[] {
  return [
    `Hi! This is a friendly, optional set of suggestions for **${report.repo.owner}/${report.repo.name}**, ` +
      `generated by [${PRODUCT_NAME}](${url()}) from the [OpenSSF Scorecard](https://securityscorecards.dev)` +
      `${report.scorecard ? ` (${report.scorecard.version})` : ""}.`,
    "",
    "None of these are required — they are common hardening steps that tend to raise a project's " +
      "supply-chain and governance signals. Take whatever is useful and ignore the rest.",
    "",
  ];
}

function pillarSection(pillar: Pillar): string[] {
  if (pillar.fixes.length === 0) return [];
  const lines: string[] = [`### ${pillar.title}`];
  for (const fix of pillar.fixes) {
    lines.push(`- **${fix.check.replace(/-/g, " ")}** — ${fix.text}`);
  }
  lines.push("");
  return lines;
}

function issueFooter(): string[] {
  return [
    "---",
    `_Assessed via ${PRODUCT_NAME} (${url()}) — an open-source trust report by Neckarshore AI. ` +
      `These are suggestions, not demands._`,
  ];
}

export function buildPillarIssueTitle(report: ReportModel, pillar: Pillar): string {
  return `${PRODUCT_NAME}: suggested ${pillar.title} improvements for ${report.repo.name}`;
}

export function buildPillarIssueMarkdown(report: ReportModel, pillar: Pillar): string {
  return [...issueIntro(report), ...pillarSection(pillar), ...issueFooter()].join("\n");
}

/** A pre-filled GitHub "new issue" URL — opens the form for the user to submit as themselves. */
export function prefilledPillarIssueUrl(report: ReportModel, pillar: Pillar): string {
  const base = `https://github.com/${report.repo.owner}/${report.repo.name}/issues/new`;
  const params = new URLSearchParams({
    title: buildPillarIssueTitle(report, pillar),
    body: buildPillarIssueMarkdown(report, pillar),
  });
  return `${base}?${params.toString()}`;
}
