import { PRODUCT_NAME, PRODUCT_SUBDOMAIN } from "@/config/product";
import type { ReportModel } from "@/lib/report-core/types";

/**
 * Build the constructive fix-issue body (work-order §4c / §6.3) — PURE + deterministic.
 * Groups the fixes by pillar and appends the required "assessed via TrustScope" attribution
 * footer (the reputation mechanism). Phrased as optional suggestions, never demands.
 */

export function buildIssueTitle(report: ReportModel): string {
  return `${PRODUCT_NAME}: suggested trust & security improvements`;
}

export function buildIssueMarkdown(report: ReportModel): string {
  const url = `https://${PRODUCT_SUBDOMAIN}`;
  const lines: string[] = [];

  lines.push(
    `Hi! This is a friendly, optional set of suggestions for **${report.repo.owner}/${report.repo.name}**, ` +
      `generated by [${PRODUCT_NAME}](${url}) from the [OpenSSF Scorecard](https://securityscorecards.dev)` +
      `${report.scorecard ? ` (${report.scorecard.version})` : ""}.`,
  );
  lines.push("");
  lines.push(
    "None of these are required — they are common hardening steps that tend to raise a project's " +
      "supply-chain and governance signals. Take whatever is useful and ignore the rest.",
  );
  lines.push("");

  for (const pillar of report.pillars) {
    if (pillar.fixes.length === 0) continue;
    lines.push(`### ${pillar.title}`);
    for (const fix of pillar.fixes) {
      lines.push(`- **${fix.check.replace(/-/g, " ")}** — ${fix.text}`);
    }
    lines.push("");
  }

  lines.push("---");
  lines.push(
    `_Assessed via ${PRODUCT_NAME} (${url}) — a reputation surface by Neckarshore AI. ` +
      `These are suggestions, not demands._`,
  );

  return lines.join("\n");
}

/** A pre-filled GitHub "new issue" URL — opens the form for the user to submit as themselves. */
export function prefilledIssueUrl(report: ReportModel): string {
  const base = `https://github.com/${report.repo.owner}/${report.repo.name}/issues/new`;
  const params = new URLSearchParams({
    title: buildIssueTitle(report),
    body: buildIssueMarkdown(report),
  });
  return `${base}?${params.toString()}`;
}
