import type { ReportModel } from "@/lib/report-core/types";
import { reportSynthesis } from "@/lib/report-summary";

/**
 * Pure, deterministic serializers (mirror lib/issue-markdown.ts): ReportModel -> string.
 * No I/O, no clock, no LLM — the same repository produces the same file (TS D9).
 * Serializes the full report, including the synthesis line and due-diligence signals (§B).
 */

export function reportToMarkdown(report: ReportModel): string {
  const r = report.repo;
  const lines: string[] = [];
  lines.push(`# Trust report — ${r.owner}/${r.name}`);
  lines.push("");
  lines.push(`> ${report.aggregateNote}`);
  lines.push("");
  lines.push(`- Repository: ${r.url}`);
  lines.push(`- Assessed: ${report.assessedAt}`);
  if (report.scorecard) lines.push(`- OpenSSF Scorecard: ${report.scorecard.version}`);
  if (r.commit) lines.push(`- Commit: ${r.commit}`);
  lines.push(`- Generated by ${report.product} — no single aggregate score, by design.`);
  lines.push("");

  // §B: the synthesis line + due-diligence signals travel with the exported report.
  lines.push("## In short");
  lines.push("");
  lines.push(reportSynthesis(report));
  lines.push("");
  if (report.dueDiligence.length > 0) {
    lines.push("## Due diligence");
    lines.push("");
    for (const s of report.dueDiligence) {
      const mitigation = s.mitigation ? ` _Mitigation: ${s.mitigation}_` : "";
      lines.push(`- **${s.title}** — ${s.detail}${mitigation}`);
    }
    lines.push("");
  }

  for (const p of report.pillars) {
    lines.push(`## Pillar ${p.id} — ${p.title}`);
    lines.push(`*${p.question}*`);
    lines.push("");
    lines.push(
      p.status === "not-assessed"
        ? `Status: not assessed. ${p.scoreBasis}`
        : `Status: assessed (${p.scoreBasis}).`,
    );
    lines.push("");
    for (const f of p.findings) {
      const sc = f.score === null ? "" : ` (${f.score}/10)`;
      lines.push(`- **${f.label}** — ${f.status}${sc}: ${f.reason}`);
    }
    if (p.findings.length) lines.push("");
    if (p.fixes.length) {
      lines.push(`**Suggested fixes:**`);
      for (const fix of p.fixes) lines.push(`- ${fix.text}`);
      lines.push("");
    }
  }
  lines.push("---");
  lines.push(
    `_Assessed via ${report.product}. Deterministic — the same repository produces the same report._`,
  );
  return lines.join("\n");
}

export function exportFilename(report: ReportModel, ext: "md" | "html"): string {
  const slug = `${report.repo.owner}-${report.repo.name}`
    .toLowerCase()
    .replace(/[^a-z0-9._-]+/g, "-")
    .replace(/^-+|-+$/g, "");
  return `${slug}-trustscope.${ext}`;
}
