import type { Band } from "@/lib/report-display";
import {
  displayDueDiligence,
  displayPillars,
  pillarBand,
  reportBodoBackdrop,
  scoreboardFill,
  tldrBand,
} from "@/lib/report-display";
import type { Finding, ReportModel } from "@/lib/report-core/types";
import { reportSynthesis } from "@/lib/report-summary";
import { BODO_ASCII } from "@/config/bodo-ascii";
import { BODO_BACKDROPS } from "@/config/bodo";
import { BODO_INLINE_SVG } from "@/config/bodo-svg";

/**
 * Pure, deterministic serializers: ReportModel -> string. No I/O, no clock, no LLM — the same
 * repository produces the same file (TS D9). The exported document mirrors the web report's
 * structure: masthead, a top scoreboard, the TL;DR (with due-diligence folded in), and one section
 * per SHOWN pillar (Functional Quality is Pro-only, so it is dropped here too). The interactive bits
 * (info affordance, convert-to-issue) are UI-only and never serialized.
 */

/** Score-first finding line: "6/10 Label — status: reason" (score leads; omitted when null). */
function findingLine(f: Finding): string {
  const sc = f.score === null ? "" : `${f.score}/10 `;
  return `- ${sc}**${f.label}** — ${f.status}: ${f.reason}`;
}

export function reportToMarkdown(report: ReportModel): string {
  const r = report.repo;
  const pillars = displayPillars(report.pillars);
  const lines: string[] = [];
  // Bodo greets the reader — a fenced ASCII banner so Markdown keeps the monospace alignment.
  // The Markdown export can't carry an SVG or a coloured disc, so the beaver is monochrome here;
  // the band signal still travels in the Pillar-scores table + the TL;DR section below.
  lines.push("```");
  lines.push(BODO_ASCII);
  lines.push("```");
  lines.push("");
  lines.push(`# Trust report — ${r.owner}/${r.name}`);
  lines.push("");
  lines.push(`> ${report.aggregateNote}`);
  lines.push("");
  lines.push(`- Repository: ${r.url}`);
  lines.push(`- Assessed: ${report.assessedAt}`);
  if (report.scorecard) lines.push(`- OpenSSF Scorecard: ${report.scorecard.version}`);
  if (r.commit) lines.push(`- Commit: ${r.commit}`);
  lines.push(`- Generated by ${report.product} — no single aggregate score, by design.`);
  lines.push("");

  // Scoreboard — the shown pillars, worst-first, at the top. Per-pillar only, never an aggregate.
  if (pillars.length > 0) {
    lines.push("## Pillar scores");
    lines.push("");
    lines.push("| Pillar | Score |");
    lines.push("| --- | --- |");
    for (const p of pillars) {
      const score = p.score === null ? "Not assessed" : `${p.score.toFixed(1)} / 10`;
      lines.push(`| Pillar ${p.id} — ${p.title} | ${score} |`);
    }
    lines.push("");
  }

  // §B: the synthesis line + due-diligence signals travel with the exported report, under TL;DR.
  lines.push("## TL;DR");
  lines.push("");
  lines.push(reportSynthesis(report));
  lines.push("");
  const dd = displayDueDiligence(report);
  if (dd.length > 0) {
    lines.push("### Due diligence — worth a second look");
    lines.push("");
    for (const s of dd) {
      const mitigation = s.mitigation ? ` _${s.mitigation}_` : "";
      lines.push(`- **${s.title}** — ${s.detail}${mitigation}`);
    }
    lines.push("");
  }

  for (const p of pillars) {
    lines.push(`## Pillar ${p.id} — ${p.title}`);
    lines.push(`*${p.question}*`);
    lines.push("");
    lines.push(
      p.status === "not-assessed"
        ? `Status: not assessed. ${p.scoreBasis}`
        : `Status: assessed (${p.scoreBasis}).`,
    );
    lines.push("");
    if (p.fixes.length) {
      lines.push(`**Suggested fix${p.fixes.length > 1 ? "es" : ""}:**`);
      for (const fix of p.fixes) lines.push(`- ${fix.text}`);
      lines.push("");
    }
    for (const f of p.findings) lines.push(findingLine(f));
    if (p.findings.length) lines.push("");
  }
  lines.push("---");
  lines.push(
    `_Assessed via ${report.product}. Deterministic — the same repository produces the same report._`,
  );
  return lines.join("\n");
}

function escapeHtml(s: string): string {
  return s.replace(
    /[&<>"]/g,
    (m) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" })[m] as string,
  );
}

// Light-theme band tints for the standalone document.
const HTML_BAND: Record<Band, { fg: string; bg: string; border: string; label: string }> = {
  concern: { fg: "#be123c", bg: "#fff1f2", border: "#fecdd3", label: "Worth a closer look" },
  moderate: { fg: "#b45309", bg: "#fffbeb", border: "#fde68a", label: "Mixed — worth a look" },
  strong: { fg: "#15803d", bg: "#f0fdf4", border: "#bbf7d0", label: "Looks solid" },
  na: { fg: "#64748b", bg: "#f8fafc", border: "#e2e8f0", label: "Not assessed" },
};

export function reportToHtml(report: ReportModel): string {
  const r = report.repo;
  const e = escapeHtml;
  const pillars = displayPillars(report.pillars);

  // Bodo's disc echoes the TL;DR ground band — the SAME source the web report + TL;DR box use, so
  // the mascot cannot drift from the report it sits on (concern→red, moderate→orange, strong→teal,
  // na→gray). Inlined so the standalone document stays self-contained.
  const bodoHex = BODO_BACKDROPS[reportBodoBackdrop(report.pillars)].hex;

  const scoreboard = pillars
    .map((p) => {
      const band = pillarBand(p.score);
      const cls = band === "na" ? "" : ` s-${band}`;
      const value =
        p.score === null
          ? `<span class="tile-na">Not assessed</span>`
          : `<span class="tile-score">${p.score.toFixed(1)}<span class="tile-max"> / 10</span></span>`;
      const fill = p.score === null ? "" : `<span style="width:${scoreboardFill(p.score)}%"></span>`;
      return `<div class="tile${cls}"><span class="tile-eyebrow">Pillar</span><span class="tile-title">${e(p.title)}</span>${value}<span class="tile-bar">${fill}</span></div>`;
    })
    .join("");
  const scoreboardSection = pillars.length
    ? `<section class="scoreboard" aria-label="Pillar scores">${scoreboard}</section>`
    : "";

  const tldr = HTML_BAND[tldrBand(report.pillars)];
  const dd = displayDueDiligence(report);
  const dueDiligence = dd.length
    ? `<h3>Due diligence — worth a second look</h3><ul>${dd
        .map(
          (s) =>
            `<li><strong>${e(s.title)}</strong> — ${e(s.detail)}${s.mitigation ? ` <em>${e(s.mitigation)}</em>` : ""}</li>`,
        )
        .join("")}</ul>`
    : "";
  const tldrSection = `<section class="tldr" style="background:${tldr.bg};border-color:${tldr.border}"><div class="tldr-head"><h2>TL;DR</h2><span class="chip" style="color:${tldr.fg}">${tldr.label}</span></div><p>${e(reportSynthesis(report))}</p>${dueDiligence}</section>`;

  const pillarSections = pillars
    .map((p) => {
      const findings = p.findings
        .map((f) => {
          const sc = f.score === null ? "" : `<span class="fsc">${f.score}/10</span> `;
          return `<li>${sc}<strong>${e(f.label)}</strong> — ${e(f.status)}: ${e(f.reason)}</li>`;
        })
        .join("");
      const fixes = p.fixes.length
        ? `<p class="fixes-h">Suggested fix${p.fixes.length > 1 ? "es" : ""}</p><ul>${p.fixes.map((fx) => `<li>${e(fx.text)}</li>`).join("")}</ul>`
        : "";
      const status =
        p.status === "not-assessed"
          ? `not assessed — ${e(p.scoreBasis)}`
          : `assessed (${e(p.scoreBasis)})`;
      return `<section id="pillar-${p.id}"><h2>Pillar ${p.id} — ${e(p.title)}</h2><p class="q">${e(p.question)}</p><p class="status">${status}</p>${fixes}<ul>${findings}</ul></section>`;
    })
    .join("");

  const sc = report.scorecard ? ` · OpenSSF Scorecard ${e(report.scorecard.version)}` : "";
  const commit = r.commit ? ` · commit ${e(r.commit.slice(0, 7))}` : "";
  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Trust report — ${e(r.owner)}/${e(r.name)}</title>
<style>:root{--ink:#1b1916;--muted:#5b6470;--line:#e4e7eb;--panel:#f7f8fa;--brand:#0d9488;--strong:#15803d;--moderate:#b45309;--concern:#be123c}*{box-sizing:border-box}body{font-family:system-ui,-apple-system,"Segoe UI",sans-serif;max-width:46rem;margin:0 auto;padding:2.5rem 1.25rem;line-height:1.6;color:var(--ink);background:#fff}a{color:inherit}.eyebrow{margin:0;font-size:.72rem;font-weight:700;letter-spacing:.14em;text-transform:uppercase;color:var(--brand)}h1{margin:.3rem 0 0;font-size:1.9rem;line-height:1.15;font-weight:700;letter-spacing:-.01em}h1 a{text-decoration:none}h1 .owner{color:var(--muted);font-weight:600}.meta{margin:.5rem 0 0;color:var(--muted);font-size:.86rem}.doctrine{margin:1.1rem 0 0;padding-left:.9rem;border-left:3px solid var(--brand);color:#3a3f46;font-size:.95rem}.masthead{display:flex;align-items:flex-start;gap:1rem}.bodo{flex:none;width:4.75rem;height:4.75rem;border-radius:50%;overflow:hidden;display:flex;align-items:center;justify-content:center;box-shadow:0 6px 22px rgba(15,23,42,.10)}.bodo svg{width:120%;height:120%;display:block}.identity{min-width:0}.scoreboard{display:grid;grid-template-columns:1fr;gap:.7rem;margin:1.75rem 0 0}@media(min-width:34rem){.scoreboard{grid-template-columns:repeat(3,1fr)}}.tile{border:1px solid var(--line);border-radius:.7rem;padding:.85rem .9rem;background:var(--panel);display:flex;flex-direction:column}.tile-eyebrow{font-size:.64rem;font-weight:700;letter-spacing:.09em;text-transform:uppercase;color:var(--muted)}.tile-title{margin:.2rem 0 .55rem;font-size:.82rem;font-weight:600;line-height:1.25;flex:1}.tile-score{font-size:1.55rem;font-weight:700;letter-spacing:-.02em;font-variant-numeric:tabular-nums}.tile-max{font-size:.8rem;font-weight:600;color:var(--muted)}.tile-na{font-size:.9rem;font-weight:600;color:#64748b}.tile-bar{display:block;height:4px;margin-top:.6rem;border-radius:2px;background:var(--line);overflow:hidden}.tile-bar>span{display:block;height:100%;border-radius:2px;background:var(--muted)}.s-strong .tile-score{color:var(--strong)}.s-strong .tile-bar>span{background:var(--strong)}.s-moderate .tile-score{color:var(--moderate)}.s-moderate .tile-bar>span{background:var(--moderate)}.s-concern .tile-score{color:var(--concern)}.s-concern .tile-bar>span{background:var(--concern)}.tldr{margin:1.6rem 0 0;padding:1.1rem 1.2rem;border:1px solid;border-radius:.7rem}.tldr-head{display:flex;align-items:center;gap:.6rem}.tldr-head h2{margin:0;font-size:1.1rem}.chip{font-size:.68rem;font-weight:700;text-transform:uppercase;letter-spacing:.06em}h2{margin:2.25rem 0 0;font-size:1.1rem;letter-spacing:-.01em}h3{margin:1.2rem 0 0;font-size:.95rem}.q{margin:.2rem 0;color:var(--muted);font-style:italic}.status{font-size:.88rem;color:#444}.fixes-h{margin-top:.6rem;font-weight:600}.fsc{font-weight:700;font-variant-numeric:tabular-nums}ul{padding-left:1.1rem}li{margin:.15rem 0}footer{margin-top:2.5rem;border-top:1px solid var(--line);padding-top:1rem;color:var(--muted);font-size:.82rem}</style>
</head><body>
<header>
<div class="masthead">
<span class="bodo" style="background:${bodoHex}">${BODO_INLINE_SVG}</span>
<div class="identity">
<p class="eyebrow">Trust report</p>
<h1><a href="${e(r.url)}"><span class="owner">${e(r.owner)}/</span>${e(r.name)}</a></h1>
<p class="meta">Assessed ${e(report.assessedAt)}${sc}${commit}</p>
</div>
</div>
<p class="doctrine">${e(report.aggregateNote)}</p>
</header>
${scoreboardSection}
${tldrSection}${pillarSections}
<footer>Assessed via ${e(report.product)} — no single aggregate score, by design. Deterministic: the same repository produces the same report.</footer>
</body></html>`;
}

export function exportFilename(report: ReportModel, ext: "md" | "html"): string {
  const slug = `${report.repo.owner}-${report.repo.name}`
    .toLowerCase()
    .replace(/[^a-z0-9._-]+/g, "-")
    .replace(/^-+|-+$/g, "");
  return `${slug}-trustscope.${ext}`;
}
